services:
  backend:
    build: ./backend/
    container_name: tracker_backend
    restart: always
    ports:
      - 5000:5000
    env_file:
      - .env

  frontend:
    build: ./frontend/
    container_name: tracker_frontend
    restart: always
    ports:
      - 8050:8050
    depends_on:
      - backend
