"""-visibility from user table

Revision ID: 1289c756f57f
Revises: c9d090d2b045
Create Date: 2025-07-31 16:26:31.923997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1289c756f57f'
down_revision: Union[str, None] = 'c9d090d2b045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calibrations', sa.Column('calibration_id', sa.String(length=15), nullable=True))
    op.create_foreign_key(None, 'calibrations', 'tools', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tools', 'users', ['issued_by'], ['id'])
    op.drop_column('tools', 'visibility')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('visibility', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tools', type_='foreignkey')
    op.drop_constraint(None, 'calibrations', type_='foreignkey')
    op.drop_column('calibrations', 'calibration_id')
    # ### end Alembic commands ###
