"""oops

Revision ID: 35d9dbd34383
Revises: 1289c756f57f
Create Date: 2025-07-31 16:49:43.985385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d9dbd34383'
down_revision: Union[str, None] = '1289c756f57f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('calibrations_parent_id_fkey', 'calibrations', type_='foreignkey')
    op.create_foreign_key(None, 'calibrations', 'tools', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calibrations', type_='foreignkey')
    op.create_foreign_key('calibrations_parent_id_fkey', 'calibrations', 'tools', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
