"""New columns

Revision ID: 59a59eda66f7
Revises: 35d9dbd34383
Create Date: 2025-07-31 18:51:57.484309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a59eda66f7'
down_revision: Union[str, None] = '35d9dbd34383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calibrations', sa.Column('last_modified', sa.DateTime(), nullable=True))
    op.add_column('calibrations', sa.Column('modified_by', sa.String(length=100), nullable=True))
    op.alter_column('calibrations', 'calibration_id',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.create_unique_constraint(None, 'calibrations', ['calibration_id'])
    op.add_column('misc_items', sa.Column('last_modified', sa.DateTime(), nullable=True))
    op.add_column('misc_items', sa.Column('modified_by', sa.String(length=100), nullable=True))
    op.add_column('roles', sa.Column('role', sa.Integer(), nullable=True))
    op.add_column('tools', sa.Column('last_modified', sa.DateTime(), nullable=True))
    op.add_column('tools', sa.Column('modified_by', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'modified_by')
    op.drop_column('tools', 'last_modified')
    op.drop_column('roles', 'role')
    op.drop_column('misc_items', 'modified_by')
    op.drop_column('misc_items', 'last_modified')
    op.drop_constraint(None, 'calibrations', type_='unique')
    op.alter_column('calibrations', 'calibration_id',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.drop_column('calibrations', 'modified_by')
    op.drop_column('calibrations', 'last_modified')
    # ### end Alembic commands ###
