"""New columns_2_3

Revision ID: 813779d2c3f2
Revises: 9c59c2e930ef
Create Date: 2025-07-31 19:55:46.221210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '813779d2c3f2'
down_revision: Union[str, None] = '9c59c2e930ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calibrations', 'modified_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('misc_items', 'modified_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('tools', 'modified_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tools', 'modified_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('misc_items', 'modified_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('calibrations', 'modified_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
