"""New columns_2_2

Revision ID: 9c59c2e930ef
Revises: b029b1be1fbc
Create Date: 2025-07-31 19:52:33.318654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c59c2e930ef'
down_revision: Union[str, None] = 'b029b1be1fbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calibrations', 'last_modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('misc_items', 'last_modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tools', 'last_modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tools', 'last_modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('misc_items', 'last_modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('calibrations', 'last_modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
