"""New columns_2

Revision ID: cc758181ffcc
Revises: 59a59eda66f7
Create Date: 2025-07-31 19:18:07.482799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc758181ffcc'
down_revision: Union[str, None] = '59a59eda66f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calibrations', 'last_modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('calibrations', 'modified_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('misc_items', 'last_modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('misc_items', 'modified_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('roles', 'role',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'roles', ['role'])
    op.alter_column('tools', 'last_modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tools', 'modified_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tools', 'modified_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('tools', 'last_modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'roles', type_='unique')
    op.alter_column('roles', 'role',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('misc_items', 'modified_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('misc_items', 'last_modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('calibrations', 'modified_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('calibrations', 'last_modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
